from distutils.core import setup
setup(
    name='genai',
    packages=['genai'],
    version='v2024',
    license='gpl-3.0',
    description='',
    author='',
    author_email='',
    url='',
    keywords=[],
    install_requires=[
          'pytest',
          'ganga',
          'pypdf',
          'FPDF',
          'tqdm',
          'numpy',
          'torch>=2.0',
          'tokenizers>=0.14.0',
          'transformers>=4.35.0',
          'accelerate',
          'sympy==1.12',
          'pebble',
          'timeout-decorator',
          'attrdict',
      ],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: GNU General Public License v3.0',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
    ],
)
